version: "3"
services:
  redis:
    container_name: redis-server
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - "$PWD/redis.conf:/usr/local/etc/redis/redis.conf"
      - "$PWD/redis:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf"
